####################################################################
####################################################################
####################################################################
####
####	LOADING PACKAGES
####	SETTING OUTPUT FILES
####
####################################################################
####################################################################
####################################################################

	# loading packages
	library(MASS)
	library(caret)
	library(data.table)
	library(DAAG)

	# setting terminal_output file
	sink("output_2.txt")
	# setting pdf_output file
	pdf("output_2.pdf")

####################################################################
####################################################################
####################################################################
####
####	SETTING UP DATA
####
####################################################################
####################################################################
####################################################################

	print("---------------------- head of Boston Data ----------------------")
	head(Boston)
	set.seed(1)

	# declaring variable with Boston data
	bostonHousing <- data.table(Boston)

	# turning chas variable into factor
	bostonHousing$chas <- as.factor(bostonHousing$chas)

	print("---------------------- structure of Boston Data ----------------------")
	str(bostonHousing)

####################################################################
####################################################################
####################################################################
####
####	GENERATING MODELS
####
####################################################################
####################################################################
####################################################################

	# generating model using the train method
	fit <- train(medv ~ .,
	                 data = bostonHousing,
	                 method = "lm",
	                 trControl = trainControl(method= "cv"))
	print("---------------------- Model Generated by train() Method ----------------------")
	fit
	print("---------------------- Final Model as Generated by train() Method ----------------------")
	fit$finalModel
	print("---------------------- Terms as Generated by train() Method ----------------------")
	fit$terms
	print("---------------------- Summary of Final Model as Generated by train() Method ----------------------")
	summary(fit$finalModel)

	
	# ------ MODEL 0
	mod <- lm(medv ~ crim + zn + indus + chas + nox + rm + age + dis + rad + tax + ptratio + black + lstat, data = Boston)
	print("---------------------- Summary of Model 0 ----------------------")
	summary(mod)
	print("---------------------- VIF of Model 0 ----------------------")
	vif(mod)

		# remove nox, rad, tax

	# ------ MODEL 1
	mod1 <- lm(medv ~ crim + zn + indus + chas + rm + age + dis + rad + tax + ptratio + black + lstat, data = Boston)
	print("---------------------- Summary of Model 1 ----------------------")
	summary(mod1)
	print("---------------------- VIF of Model 1 ----------------------")
	vif(mod1)

	# ------ MODEL 2
	mod2 <- lm(medv ~ crim + zn + indus + chas + nox + rm + age + dis + ptratio + black + lstat, data = Boston)
	print("---------------------- Summary of Model 2 ----------------------")
	summary(mod2)
	print("---------------------- VIF of Model 2 ----------------------")	
	vif(mod2)

	# ------ MODEL 3
	mod3 <- lm(medv ~ crim + zn + chas + nox + rm + dis + ptratio + black + lstat, data = Boston)
	print("---------------------- Summary of Model 3 ----------------------")
	summary(mod3)
	print("---------------------- VIF of Model 3 ----------------------")
	vif(mod3)
	# plot
	plot(mod3)

####################################################################
####################################################################
####################################################################
####
####	CROSS VALIDATION
####
####################################################################
####################################################################
####################################################################

	print("---------------------- Cross Validation for Model 1 ----------------------")
	cvfit <- CVlm(data = bostonHousing, form.lm = formula(mod1), m = 10, dots = FALSE, seed = 1, plotit = c("Observed", "Residual"), main = "Cross-validation for mod1", legend.pos="topleft", printit = TRUE)

	print("---------------------- Cross Validation for Model 2 ----------------------")
	cvfit <- CVlm(data = bostonHousing, form.lm = formula(mod2), m = 10, dots = FALSE, seed = 1, plotit = c("Observed", "Residual"), main = "Cross-validation for mod2", legend.pos="topleft", printit = TRUE)

	print("---------------------- Cross Validation for Model 3 ----------------------")
	cvfit <- CVlm(data = bostonHousing, form.lm = formula(mod3), m = 10, dots = FALSE, seed = 1, plotit = c("Observed", "Residual"), main = "Cross-validation for mod3", legend.pos="topleft", printit = TRUE)